### ISSUE TITLE
Stack-based LL Parser

### ISSUE THREAD

**Issue by M0ST4FA** [M0ST4FA/RegEx#9]
## Tasks:
- [x] Create basic LL(1) parser.
- [x] Add panic mode error recovery.
- [x] Add semantic action support.
